# ./frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Run your "dev" script from package.json
# We add "--" "--host" to make the Vite server accessible
# outside the container.
CMD [ "npm", "run", "dev", "--", "--host" ]