# ./backend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Run your "dev" script from package.json
CMD [ "npm", "run", "dev" ]